import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type GLTFResult = GLTF & {
  nodes: {
    blueButton_geo: THREE.Mesh;
    button_01: THREE.Mesh;
    button_02: THREE.Mesh;
    button_03: THREE.Mesh;
    button_04: THREE.Mesh;
    button_05: THREE.Mesh;
    button_06: THREE.Mesh;
    button_07: THREE.Mesh;
    button_08: THREE.Mesh;
    button_09: THREE.Mesh;
    button_10: THREE.Mesh;
    button_11: THREE.Mesh;
    button_12: THREE.Mesh;
    button_13: THREE.Mesh;
    button_14: THREE.Mesh;
    button_15: THREE.Mesh;
    button_16: THREE.Mesh;
    button_17: THREE.Mesh;
    button_18: THREE.Mesh;
    button_19: THREE.Mesh;
    button_20: THREE.Mesh;
    button_21: THREE.Mesh;
    button_22: THREE.Mesh;
    button_23: THREE.Mesh;
    button_24: THREE.Mesh;
    button_25: THREE.Mesh;
    cloud001: THREE.Mesh;
    cloud002: THREE.Mesh;
    cloud003: THREE.Mesh;
    cloud004: THREE.Mesh;
    cloud005: THREE.Mesh;
    cloud006: THREE.Mesh;
    cloud007: THREE.Mesh;
    cloud008: THREE.Mesh;
    cloud009: THREE.Mesh;
    eyeball_geo: THREE.Mesh;
    items_geo: THREE.Mesh;
    land_geo: THREE.Mesh;
    ocean_geo: THREE.Mesh;
    water_geo: THREE.Mesh;
    snow_land_geo: THREE.Mesh;
    lake_geo: THREE.Mesh;
    greenButton_geo: THREE.Mesh;
    yellowButton_geo: THREE.Mesh;
  };
};
